### ISSUE TITLE
Mechanical build instructions are vague

### ISSUE THREAD

**Issue by daveloyall** [evildmp/BrachioGraph#10]
Hi.  I can't tell how to build the mechanism.  I can see from the pictures that apparently you just glue the sticks to the motor shaft/arm?  But what about the third motor at the pen end?  What is the moving part of that motor attached to?

**Comment by evildmp** [comment]
In all cases, the motors have "horns", the little plastic arms you can see in the photos. These fit snugly over the gear-shaft of each motor. I've added new images to https://brachiograph.readthedocs.io/en/latest/get-started/build.html.

**Comment by daveloyall** [comment]
The improvements are good!  Thank you!
