### ISSUE TITLE
Wiring diagram

### ISSUE THREAD

**Issue by AlStal** [evildmp/BrachioGraph#11]
A simple wiring diagram would be great, for either the servo wiring harness or the breadboard option (where the documentation states the RPi doesn't have enough 5v sources to drive all 3 servos).
Thank you

**Comment by willward1** [comment]
I was a bit confused about this also. I got it to work by
1. connecting the + wires of all 3 servos together, and then into one of the 5v pins of the pi
2. connecting all of the ground wires of all three servos,and then into the ground pin of the pi
3. connecting the data wire of all three servos (usually the orange one) and into the GIPO pins 14,15,and 18 of the pi.  

Quick and dirty diagram:
![Wiring Diagram](https://user-images.githubusercontent.com/6721096/67429816-ed8bfd80-f5ae-11e9-93cd-6947cf684dbc.png)

**Comment by AlStal** [comment]
Perfect, thank you

**Comment by Level0gamedev** [comment]
Thank you @willward1 - I came here with the exact same question!

**Comment by evildmp** [comment]
I found it useful not to touch the wires of the servos themselves, but to splice and solder some ribbon cable extensions.

**Comment by willprice** [comment]
![brachiograph_bb](https://user-images.githubusercontent.com/966205/69915427-acf19080-1446-11ea-965a-84ed4aced178.png)

Here's a fritzing diagram I put together
