### ISSUE TITLE
Installing pillow: "E: Unable to locate package libwebpmux3"

### ISSUE THREAD

**Issue by willward1** [evildmp/BrachioGraph#18]
When I try to install pillow using the command provided:

`sudo apt install libwebp6 libtiff5 libjbig0 liblcms2-2 libwebpmux3 libopenjp2-7 libzstd1 libwebpdemux2`

I get the error message: 

"E: Unable to locate package libwebpmux3"

**Comment by Findus23** [comment]
Which debian version are you using?
libwebpmux3 is only available on buster and later.

**Comment by evildmp** [comment]
I think you can probably safely leave ``libwebpmux3`` out, unless you are one of the few people who uses WepB...

**Comment by willward1** [comment]
That worked -thanks!
