### ISSUE TITLE
Request for more information about different servo models

### ISSUE THREAD

**Issue by evildmp** [evildmp/BrachioGraph#31]
I would like to gather more information about different servo models to include in the documentation.

If you have built a plotter, please add a note here about what servos you used, and the results you obtained.  The code now includes two new methods, ``BrachioGraph.vertical_lines()`` and ``BrachioGraph.horizontal_lines()``; it might also be useful to include a picture of the results from these.

**Comment by jkrauska** [comment]
Bought more expensive Digital servos - [TowerPro SG92R](https://www.amazon.com/gp/product/B01CX63AOQ/) and found them much quicker, but also much more 'twitchy' and prone to unstable feedback oscillations.

Replaced with [Miuzei SG90 9G](https://www.amazon.com/gp/product/B072V529YD/) and have had much more stable results.
