### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by raphaelbastide** [evildmp/BrachioGraph#8]
A short video of BrachioGraph in action would be really helpful to get an idea of the dynamics of the drawing process.

**Comment by willward1** [comment]
Here is a time lapse video of one print. The full print took ~25 min.  
https://www.youtube.com/watch?v=18T0IQNadbw&feature=youtu.be

**Comment by raphaelbastide** [comment]
This is a cool video, I suggest to add it to the doc!

**Comment by evildmp** [comment]
Video is now included in the documentation.
