### ISSUE TITLE
" pigpio.error: 'pulsewidth not 0 or 500-2500' " error. PLEASE HELP

### ISSUE THREAD

**Issue by bob486** [evildmp/BrachioGraph#95]
Whenever I put in the test command `bg.test_pattern()` the servos move a little bit and then I get this error:
```
raceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/BrachioGraph/brachiograph.py", line 332, in test_pattern
    self.xy(bounds[0],   y,     wait, interpolate)
  File "/home/pi/BrachioGraph/brachiograph.py", line 475, in xy
    self.set_angles(angle_1, angle_2)
  File "/home/pi/BrachioGraph/brachiograph.py", line 501, in set_angles
    self.set_pulse_widths(pw_1 + self.active_hysteresis_correction_1, pw_2 + self.active_hysteresis_correction_2)
  File "/home/pi/BrachioGraph/brachiograph.py", line 548, in set_pulse_widths
    self.rpi.set_servo_pulsewidth(14, pw_1)
  File "/home/pi/.local/lib/python3.7/site-packages/pigpio.py", line 1677, in set_servo_pulsewidth
    self.sl, _PI_CMD_SERVO, user_gpio, int(pulsewidth)))
  File "/home/pi/.local/lib/python3.7/site-packages/pigpio.py", line 1009, in _u2i
    raise error(error_text(v))
pigpio.error: 'pulsewidth not 0 or 500-2500'
```

How would I fix this? Would appreciate any help! I am using the [ES08MAII ](https://www.amazon.com/ES08MA-Metal-Analog-Servo-Model/dp/B07KYK9N1G)servos.

**Comment by spheppner** [comment]
yes i get the same error. please fix this

**Comment by E0175137** [comment]
Same, I got stuck on this error, please advise.

**Comment by bob486** [comment]
Yeah.

**Comment by evildmp** [comment]
The bounds of the box you are trying to draw the test pattern in are too large, and the pulse-widths required to meet them exceed the allowed values (500-2500mS).

The new default BrachioGraph definition https://github.com/evildmp/BrachioGraph/blob/master/brachiograph.py#L19-L40 and clearer getting-started guide should ensure that you stay within limits.

**Comment by bob486** [comment]
I tried the new updated version and it worked. Thank you very much for the help!
